# This is the maximum signal switches a redstone wire may experience within the below configured time period before RSCP acts
MaxSignalChanges: 1500
# This is above described time period (in seconds)
TimePeriod: 3
# Should notify them who have the permission rscp.getnotified about new found and blocked redstone clocks?
NotifyAdmins: false
# The clock will be stopped by replacing a redstone with a block which you can decide here
# It can be a SAPLING, WATER and even AIR, but if you want a written sign remember to write SIGN_POST
ClockBlocker: SIGN_POST
# This part is only relevant if ClockBlocker is set to SIGN_POST
Sign:
# A sign has four lines. Edit them here.
  Line1: 'Redstone-Clocks'
  Line2: 'are'
  Line3: '&4FORBIDDEN!'
  Line4: ''
# Here you can add worlds in which the plugin should check on redstone clocks and stop them
Worlds:
- world
- world_nether
- world_the_end
# These features only work if you have the plugin WorldGuard on your server!
WorldGuard:
# Redstone clocks in these regions will not get blocked by this plugin
  RegionWhitelist:
  - redstone
  - area